# Generated by Django 2.2.6 on 2019-10-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('other_names', models.CharField(max_length=250)),
                ('filled', models.CharField(max_length=250)),
                ('id_number', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('race', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=250)),
                ('dob', models.DateField(max_length=10)),
                ('occupation', models.CharField(max_length=250)),
                ('income', models.CharField(max_length=250)),
                ('education', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
